CREATE TABLE `AnalyticsEvent` (
    `id` VARCHAR(191) NOT NULL,
    `eventType` VARCHAR(48) NOT NULL,
    `visitorId` VARCHAR(80) NOT NULL,
    `sessionId` VARCHAR(80) NOT NULL,
    `route` VARCHAR(255) NOT NULL,
    `vehicleId` VARCHAR(191) NULL,
    `vehicleSlug` VARCHAR(180) NULL,
    `vehicleLabel` VARCHAR(240) NULL,
    `searchTerm` VARCHAR(180) NULL,
    `makeSlug` VARCHAR(120) NULL,
    `fuelTypeSlug` VARCHAR(120) NULL,
    `sort` VARCHAR(32) NULL,
    `resultCount` INTEGER NULL,
    `referrer` VARCHAR(500) NULL,
    `utmSource` VARCHAR(120) NULL,
    `utmMedium` VARCHAR(120) NULL,
    `utmCampaign` VARCHAR(160) NULL,
    `deviceType` VARCHAR(24) NULL,
    `metadata` JSON NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `AnalyticsEvent_createdAt_eventType_idx`(`createdAt`, `eventType`),
    INDEX `AnalyticsEvent_eventType_createdAt_idx`(`eventType`, `createdAt`),
    INDEX `AnalyticsEvent_vehicleId_eventType_createdAt_idx`(`vehicleId`, `eventType`, `createdAt`),
    INDEX `AnalyticsEvent_visitorId_createdAt_idx`(`visitorId`, `createdAt`),
    INDEX `AnalyticsEvent_sessionId_createdAt_idx`(`sessionId`, `createdAt`),
    INDEX `AnalyticsEvent_searchTerm_createdAt_idx`(`searchTerm`, `createdAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
